### ISSUE TITLE
Using with_deleted on belongs_to breaks class reflections?

### ISSUE THREAD

**Issue by ruprict** [ActsAsParanoid/acts_as_paranoid#28]
I am upgrading a Rails 3.2 app to 4.0 that uses acts_as_paranoid, and I've switched to this gem.  After upgrading, many of tests were failing with 

```
NoMethodError (undefined method `parent_reflection' for true:TrueClass):
```

which was coming from the ActiveRecord `reflections` method. Each association in AR adds an entry to the `_reflections` hash. When I do something like:

```
class Child < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :parent, with_deleted: true
end
```

it adds a (seemingly) bogus entry into `_reflections`

```
Child._reflections.keys => ["parent", :with_deleted]
Child.reflections => NoMethodError (undefined method `parent_reflection' for true:TrueClass)
```

(the `with_deleted` value is `true` in the hash)

I have confirmed this is a brand new, vanilla Rails project. If I comment out  https://github.com/ActsAsParanoid/acts_as_paranoid/blob/master/lib%2Facts_as_paranoid%2Fassociations.rb#L16 then the error goes away. It seems that added `with_deleted` to the result is bad...should it be removed? Or am I using this incorrectly?  

I'll gladly issue a PR to remove that line, but I am not convinced enough that I am not just being stupid.

**Comment by pkarman** [comment]
+1 to this problem, also seen when migrating from Rails 3.2 to 4.2.

**Comment by itsNikolay** [comment]
+ 1 from rails 3 to 4 migration

**Comment by zzak** [comment]
This should be fixed by now, can you confirm? <3

**Comment by ruprict** [comment]
Unfortunately, I have moved on from that project and can't confirm it. Any chance one of the other commenters can check it easily?

**Comment by pkarman** [comment]
I've also moved on from that project. We moved entirely away from this gem in the meantime:
https://github.com/popuparchive/pop-up-archive/blob/master/Gemfile#L90

**Comment by zzak** [comment]
I belive this was fixed by e8f7fbb1004c010e87cd11e648a914621c367043 and released in `0.5.0.beta2`.

If you're still having this issue please re-open the ticket.

Thank you!

**Comment by bjeanes** [comment]
I _think_ this is a similar underlying issue but with accessing `proxy_association`. This is _also_ upgrading from Rails 3 to 4 (and AAP 0.4.5 -> 0.5.0):

``` ruby
# illustrative code only, loosely based on my situation
class User < ActiveRecord::Base
  has_many :projects, through: :collaboratorships do
    def owned
      where('projects.owner_id = ?', proxy_association.owner.id)
    end

    def collaborated
      where('projects.owner_id <> ?', proxy_association.owner.id)
    end
  end
end

# In Rails 3.2.22.5, with AAP 4.5:
current_user.projects.with_deleted.collaborated #=> [#<Project ...>, ...]
current_user.projects.collaborated.with_deleted #=> [#<Project ...>, ...]

# In Rails 4.0.13, with AAP 4.0:
current_user.projects.with_deleted.collaborated #=> NoMethodError: undefined local variable or method `proxy_association' for #<ActiveRecord::Relation []>
current_user.projects.collaborated.with_deleted #=> [#<Project ...>, ...]
```

I know these are all old and unmaintained versions of things so I'm not so much posting here with the expectation that it will be fixed, but for documentation purposes in case others run into it too. This GH issue seems the closest likely relative to my issue but was not fixed by e8f7fbb so probably distinct in cause.

In my case, as can be seen above, putting `with_deleted` last resolves the issue for me. However, whatever scope is returned by `with_deleted` loses its proxy context.
