### ISSUE TITLE
validates_as_paranoid not working

### ISSUE THREAD

**Issue by Abhimaropost** [ActsAsParanoid/acts_as_paranoid#113]
validates_as_paranoid is not working with rails 5.2.  Its giving undefined local variable or method `validates_as_paranoid' for #<Class:> error, while adding in model

**Comment by Eth3rnit3** [comment]
The same !

**Comment by mvz** [comment]
@Abhimaropost or @Eth3rnit3 are you still experiencing this and if so, can you post some example code?

**Comment by omairrazam** [comment]
Got same error. @mvz 

`class Paranoiac < ActiveRecord::Base
  acts_as_paranoid
  validates_as_paranoid
end`

its standard integration no specific logic

**Comment by mvz** [comment]
Thanks, @omairrazam.

@Abhimaropost and @Eth3rnit3 can you confirm that you're using `acts_as_paranoid` and not `paranoia`?

**Comment by Eth3rnit3** [comment]
Sorry for my inattention, I'm using paranoia.

**Comment by mvz** [comment]
I'm closing this for now. @Abhimaropost if you feel this issue does apply to `acts_as_paranoid` please let me know and I'll reopen it.
