### ISSUE TITLE
Scope chaining broken on Rails 4.2.5.1?

### ISSUE THREAD

**Issue by timfenney** [ActsAsParanoid/acts_as_paranoid#46]
Hey there,

Just having some issues with scope chaining on Rails 4.2.5.1.

This works in Rails 3.7

```ruby
SomeModel.unscoped.with_deleted
```

However, in our Rails app on 4.2.5.1 it doesn't; we get a NoMethodError for undefined method `with_default_scope`.

The issue seems to be with `lib/core/acts_as_paranoid/core.rb`, line 82. That is calling the query method that was present in Rails 3 but not 4 AFAICT.

The temporary workaround seems to be to not use `unscoped` in scopes for chaining upstream from e.g. `with_deleted`.

Could we please get a fix for this?

**Comment by zzak** [comment]
@mvz Do you have any ideas about this?

It seems like it might be related to 3bf46c2364b8d1256467211e92e6272a99f1e87a or 01bdce8585e15d05de8c38fc874183e6df590c83

**Comment by mvz** [comment]
Yes, I kind of see what happens: `.without_paranoid_default_scope` does a check that is supposed to differentiate between AR4.1 and lower. But since `.unscoped` already removes the acts as paranoid scope, the check has the wrong result.

That needs to be fixed of course, but I do wonder why you would call `.unscoped.with_deleted`, since the `.unscoped` should already give you the deleted records. @timfenney can you shed some light on that please?

**Comment by mvz** [comment]
I'll see if I can provide a fix as well.

**Comment by zzak** [comment]
@mvz Thank you! :bow:

**Comment by timfenney** [comment]
Now that you mention it I am not sure of the utility of the scope chaining example I had provided. It is probably just that that was in our codebase somewhere, and tests started failing after upgrade to Rails 4.whatever.

**Comment by mvz** [comment]
I tried to reproduce this on current master and failed. Then I discovered this was already fixed in 17ce017c4bc8e96fb9f76f814cb36e917742ac60, with proper checks for the AR version :smile:.

**Comment by zzak** [comment]
Great, thank you @mvz for your investigation <3 <3 <3

Closing this then!
