### ISSUE TITLE
acts_as_paranoid breaks other gems in rails 5.2.0.rc1

### ISSUE THREAD

**Issue by pyromaniackeca** [ActsAsParanoid/acts_as_paranoid#94]
Hello, when upgrading rails from 5.1.5 to 5.2.0.rc1, our application stopped working. I've concluded that the source of the issue is `acts_as_paranoid`, for when removing the gem, the application works as expected. Bellow is the error output when running specs:

```
Bundler::GemRequireError: There was an error while trying to load the gem 'audited'.
Gem Load Error is: undefined method `arity' for {:polymorphic=>true}:Hash
Backtrace for gem load error is:
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/associations/builder/association.rb:51:in `build_scope'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/associations/builder/association.rb:43:in `create_reflection'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/associations/builder/association.rb:31:in `build'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/associations.rb:1654:in `belongs_to'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/acts_as_paranoid-085b5cc6da14/lib/acts_as_paranoid/associations.rb:14:in `belongs_to_with_deleted'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/audited-4.7.0/lib/audited/audit.rb:37:in `<class:Audit>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/audited-4.7.0/lib/audited/audit.rb:36:in `<module:Audited>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/audited-4.7.0/lib/audited/audit.rb:3:in `<top (required)>'
```
I believe the source of the issue is this: https://github.com/rails/rails/commit/9b53f74d897d346f44caae7b0cffcd900f986259#diff-5870816b49b90e43340607bb11ed2514L41

**Comment by luizkowalski** [comment]
I have the same issue, but I'm trying to load the app

```
/Users/luizkowalski/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:51:in `build_scope': undefined method `arity' for {:polymorphic=>true, :optional=>true}:Hash (NoMethodError)
```

**Comment by mvz** [comment]
Should be fixed in 0.6.0 :tada:.
